FROM node:14-alpine as builder
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package*.json ./
RUN npm install

FROM node:14-alpine as test
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY --from=builder /app/node_modules/ /app/node_modules/
COPY . .
ENV CI=true
RUN npm test || true

FROM node:14-alpine as delivery
WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY --from=builder /app/node_modules/ /app/node_modules/
COPY . . 
CMD ["npm", "start"]

